name: deploy lambda

on:
  push:
    branches: [ master ]
    paths:
      # only commits containing changes under these paths will trigger this workflow
      - 'code/**'
      
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./terraform
    steps:
    - uses: actions/checkout@v1
    
    - uses: hashicorp/setup-terraform@v1
      with:
       terraform_version: 1.1.4
         
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: touch prog.zip && terraform init

    - name: Terraform validation
      run: terraform validate
      
          
    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve --var-file values.tfvar
      
    - name: Upload zip file
      uses: actions/upload-artifact@v2
      with:
        name: prog
        path: prog.zip
